baseURL = 'https://no5tyle.github.io'
languageCode = 'en-us'
title = 'nostyle.systems'

theme = ["kaslaanka", "hugo-shortcode-gallery"]

[params]
sitename = "nostyle.systems"
copyrights = "Simon Fuller"
defaultList = "global"
paginationLen = 3
projectsURL = "https://no5tyle.github.io"

[[menu.primary]]
name = "About"
url = "/"
weight = 2

[[menu.primary]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.primary]]
name = "Collection"
url = "/collection"
weight = 4

[[menu.primary]]
name = "Posts"
url = "/blog"
weight = 5

[[menu.primary]]
name = "Contact"
url = "/contact"
weight = 6