baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = 'kaslaanka'

[params]
sitename = "nostyle.systems"
copyrights = "Simon Fuller"
defaultList = "global"
paginationLen = 3
projectsURL = "https://nostyle.systems"

[[params.myprojects]]
name = "Totally Awesome Project"
description = "Machine Learning Magic!!!"
url = "https://example.com"

[[params.myprojects]]
name = "Kaslaanka"
description = "The best hugo theme ever!!!"
url = "https://github.com/M1cR0xf7/kaslaanka"

[[menu.primary]]
name = "About"
url = "/"
weight = 2

[[menu.primary]]
name = "Projects"
url = "/projects.xml"
weight = 3

[[menu.primary]]
name = "Collection"
url = "/collection.xml"
weight = 4

[[menu.primary]]
name = "Posts"
url = "/posts.xml"
weight = 5

[[menu.primary]]
name = "Contact"
url = "/contact.xml"
weight = 6